export enum Status {
  ACTIVE = 'active',
  INACTIVE = 'inactive',
  PENDING = 'pending',
  DELETED = 'deleted',
  VERIFIED = 'verified',
  UNVERIFIED = 'unverified',
  APPROVED = 'approved',
  UNAPPROVED = 'unapproved',
  REJECTED = 'rejected',
  ACCEPTED = 'accepted',
  FAILED = 'failed',
  COMPLETED = 'completed',
  INCOMPLETE = 'incomplete',
  BLOCKED = 'blocked',
  INITIATED = 'initiated',
  NOT_STARTED = 'not_started',
  PAUSED = 'paused',
  STOPPED = 'stopped'
}
